### PR TITLE
Create bennyupdate

### PR DESCRIPTION
**Pull request by b3nnee**
Hi I am new to this (Github). I modified / extended your incredible library, to include more data types for storage and titles in alerts, inputs etc. Also added an input dialog for passwords, could have made it a bit shorter though (by simply adding an extra arg to your function) now that I think of it. Instead of overwriting your code, I wanted to add to it. 

You may look at it and take bits and pieces that are useful and add it to the original library, I guess it could help others.

Cheers.

### CODE REVIEW

**Comment by louislam** [comment]
Hi Benny,
Nice to meet you! I am new to GitHub too.

I am very surprised that you enhanced my library. The storage part and the login dialog part are wonderful. 
However, it seems that your pull request doesn't include the newest version of your code? Could you check?

And here are some suggestions for you:
1. We should not remove the old method signatures when we are writing a library, because once we do this, if there are any users using the old version of the library, and update to the newest version. Because of removing method signatures, users' application may got so many error.
2. Keep variable names simple. For example, "title", add "ben" behind which may confuses users, lol.
3. Following Java's naming convention, e.g.: is_visible => isVisble. '

Actually, I am not a native English speaker, hope you know what I mean if there are some grammar mistakes.
Thank you for your effort!

Louis.

**Comment by b3nnee** [comment]
Hi Louis,
Yeah actually it's my first time working on a library. I just wanted to use the extensions quickly in my android app code and wasn't thinking of the conventions (my bad). I am glad you get the main idea/reason for my extensions. You can rename all the variables, add proper method signatures etc. You can use the code in anyway to update the original you created... at your own convenience of course. ;) 

Thanks again for the library, very nice work indeed.

**Comment by louislam** [comment]
Haha, you did a great job too! Thanks.

**Comment by louislam** [comment]
v1.1

**Pull request closed without merging**
